import {
  AssignmentRuleType,
  FollowUpStatus,
  LeadPriority,
  LeadSource,
  LeadStatus,
  MessageDirection,
  NotificationKind,
  SalesActivityType,
} from '../../../../sales/domain/sales.enums';

const now = Date.now();
export const mins = (n: number) => new Date(now - n * 60_000);
export const hours = (n: number) => new Date(now - n * 3_600_000);
export const days = (n: number) => new Date(now - n * 86_400_000);

export const NAIROBI_DEMO_LEADS = [
  {
    demoKey: 'lead-001',
    branchCode: 'WST',
    source: LeadSource.Whatsapp,
    status: LeadStatus.New,
    priority: LeadPriority.Urgent,
    customerName: 'Brian Mwangi',
    customerPhone: '+254712555001',
    interestSummary: 'Toyota Prado 2021 — financing & trade-in',
    assigneeEmail: 'sales@dealrstack.com',
    assignmentReason: 'Round robin (SUV leads)',
    unread: true,
    slaDueAt: mins(8),
    lastActivityAt: mins(4),
    createdAt: mins(12),
    conversationDemoKey: 'conv-001',
  },
  {
    demoKey: 'lead-002',
    branchCode: 'MBR',
    source: LeadSource.Jiji,
    status: LeadStatus.Contacted,
    priority: LeadPriority.High,
    customerName: 'Faith Njeri',
    customerPhone: '+254733555002',
    interestSummary: 'Mazda CX-5 — cash buyer, viewing Saturday',
    assigneeEmail: 'brian@nairobi-auto-hub.co.ke',
    assignmentReason: 'Branch: Mombasa Road',
    unread: false,
    slaDueAt: hours(2),
    lastActivityAt: hours(1),
    createdAt: days(1),
    conversationDemoKey: 'conv-002',
  },
  {
    demoKey: 'lead-003',
    branchCode: 'WST',
    source: LeadSource.Website,
    status: LeadStatus.Qualified,
    priority: LeadPriority.Normal,
    customerName: 'Daniel Kipchoge',
    customerPhone: '+254711555003',
    interestSummary: 'Fleet quote — 3 double-cab pickups',
    assigneeEmail: 'grace@nairobi-auto-hub.co.ke',
    assignmentReason: 'Manual assign (fleet)',
    unread: true,
    slaDueAt: hours(6),
    lastActivityAt: hours(3),
    createdAt: days(2),
  },
  {
    demoKey: 'lead-004',
    branchCode: 'WST',
    source: LeadSource.Facebook,
    status: LeadStatus.Nurturing,
    priority: LeadPriority.Normal,
    customerName: 'Linet Akinyi',
    customerPhone: '+254798555004',
    interestSummary: 'Subaru Forester — comparing with RAV4',
    assigneeEmail: 'sales@dealrstack.com',
    assignmentReason: 'Vehicle type: SUV',
    unread: false,
    slaDueAt: days(1),
    lastActivityAt: days(1),
    createdAt: days(4),
    conversationDemoKey: 'conv-003',
  },
  {
    demoKey: 'lead-005',
    branchCode: 'MBR',
    source: LeadSource.WalkIn,
    status: LeadStatus.Contacted,
    priority: LeadPriority.High,
    customerName: 'Samuel Ochieng',
    customerPhone: '+254722555005',
    interestSummary: 'Mercedes C200 — test drive booked',
    assigneeEmail: 'tenant-admin@dealrstack.com',
    assignmentReason: 'Owner escalation (high value)',
    unread: false,
    slaDueAt: hours(4),
    lastActivityAt: mins(45),
    createdAt: days(1),
    conversationDemoKey: 'conv-004',
  },
  {
    demoKey: 'lead-006',
    branchCode: 'WST',
    source: LeadSource.Instagram,
    status: LeadStatus.New,
    priority: LeadPriority.Normal,
    customerName: 'Wanjiru Maina',
    customerPhone: '+254701555006',
    interestSummary: 'Honda Fit hybrid — budget KES 1.8M',
    assigneeEmail: null,
    assignmentReason: null,
    unread: true,
    slaDueAt: mins(15),
    lastActivityAt: mins(15),
    createdAt: mins(15),
    conversationDemoKey: 'conv-005',
  },
  {
    demoKey: 'lead-007',
    branchCode: 'MBR',
    source: LeadSource.Phone,
    status: LeadStatus.Lost,
    priority: LeadPriority.Low,
    customerName: 'Kevin Mutua',
    customerPhone: '+254745555007',
    interestSummary: 'BMW X3 — bought elsewhere',
    assigneeEmail: 'brian@nairobi-auto-hub.co.ke',
    assignmentReason: 'Geography: Kiambu',
    unread: false,
    slaDueAt: days(3),
    lastActivityAt: days(3),
    createdAt: days(10),
  },
  {
    demoKey: 'lead-008',
    branchCode: 'WST',
    source: LeadSource.Cheki,
    status: LeadStatus.Won,
    priority: LeadPriority.Normal,
    customerName: 'Esther Wambui',
    customerPhone: '+254726555008',
    interestSummary: 'Toyota Vitz — deposit paid',
    assigneeEmail: 'sales@dealrstack.com',
    assignmentReason: 'Round robin',
    unread: false,
    slaDueAt: days(5),
    lastActivityAt: days(2),
    createdAt: days(14),
    conversationDemoKey: 'conv-006',
  },
  {
    demoKey: 'lead-009',
    branchCode: 'WST',
    source: LeadSource.Csv,
    status: LeadStatus.New,
    priority: LeadPriority.Normal,
    customerName: 'Import Motors Ltd',
    customerPhone: '+254720555009',
    interestSummary: 'Bulk inquiry — 5 sedans under KES 2.5M',
    assigneeEmail: 'grace@nairobi-auto-hub.co.ke',
    assignmentReason: 'Manual assign (B2B)',
    unread: true,
    slaDueAt: hours(8),
    lastActivityAt: hours(5),
    createdAt: hours(6),
  },
  {
    demoKey: 'lead-010',
    branchCode: 'MBR',
    source: LeadSource.Manual,
    status: LeadStatus.Contacted,
    priority: LeadPriority.Urgent,
    customerName: 'Charles Ndungu',
    customerPhone: '+254799555010',
    interestSummary: 'Land Cruiser V8 — corporate lease',
    assigneeEmail: 'tenant-admin@dealrstack.com',
    assignmentReason: 'Availability: senior closer online',
    unread: true,
    slaDueAt: mins(20),
    lastActivityAt: mins(18),
    createdAt: hours(2),
    conversationDemoKey: 'conv-007',
  },
] as const;

export const NAIROBI_DEMO_DEALS = [
  {
    demoKey: 'deal-001',
    leadDemoKey: 'lead-001',
    stageKey: 'negotiation',
    title: 'Brian Mwangi — Prado 2021',
    valueKes: 8_500_000,
    assigneeEmail: 'sales@dealrstack.com',
    assignmentReason: 'Round robin (SUV leads)',
    lastActivityAt: mins(4),
    createdAt: days(2),
    inactiveDays: 0,
    slaDueAt: hours(4),
    conversationDemoKey: 'conv-001',
  },
  {
    demoKey: 'deal-002',
    leadDemoKey: 'lead-002',
    stageKey: 'test_drive',
    title: 'Faith Njeri — Mazda CX-5',
    valueKes: 3_200_000,
    assigneeEmail: 'brian@nairobi-auto-hub.co.ke',
    lastActivityAt: hours(1),
    createdAt: days(3),
    inactiveDays: 0,
    slaDueAt: hours(12),
    conversationDemoKey: 'conv-002',
  },
  {
    demoKey: 'deal-003',
    leadDemoKey: 'lead-003',
    stageKey: 'interested',
    title: 'Daniel Kipchoge — Fleet pickups',
    valueKes: 12_000_000,
    assigneeEmail: 'grace@nairobi-auto-hub.co.ke',
    lastActivityAt: hours(3),
    createdAt: days(4),
    inactiveDays: 1,
  },
  {
    demoKey: 'deal-004',
    leadDemoKey: 'lead-004',
    stageKey: 'contacted',
    title: 'Linet Akinyi — Forester',
    valueKes: 4_100_000,
    assigneeEmail: 'sales@dealrstack.com',
    lastActivityAt: days(1),
    createdAt: days(5),
    inactiveDays: 2,
    slaDueAt: days(2),
    conversationDemoKey: 'conv-003',
  },
  {
    demoKey: 'deal-005',
    leadDemoKey: 'lead-005',
    stageKey: 'deposit_paid',
    title: 'Samuel Ochieng — C200',
    valueKes: 5_800_000,
    assigneeEmail: 'tenant-admin@dealrstack.com',
    lastActivityAt: mins(45),
    createdAt: days(6),
    inactiveDays: 0,
    conversationDemoKey: 'conv-004',
  },
  {
    demoKey: 'deal-006',
    leadDemoKey: 'lead-006',
    stageKey: 'new_lead',
    title: 'Wanjiru Maina — Honda Fit',
    valueKes: 1_800_000,
    assigneeEmail: 'sales@dealrstack.com',
    lastActivityAt: mins(15),
    createdAt: mins(15),
    inactiveDays: 0,
    slaDueAt: mins(30),
    conversationDemoKey: 'conv-005',
  },
  {
    demoKey: 'deal-007',
    leadDemoKey: 'lead-007',
    stageKey: 'lost',
    title: 'Kevin Mutua — BMW X3',
    valueKes: 6_200_000,
    assigneeEmail: 'brian@nairobi-auto-hub.co.ke',
    lastActivityAt: days(3),
    createdAt: days(12),
    inactiveDays: 3,
  },
  {
    demoKey: 'deal-008',
    leadDemoKey: 'lead-008',
    stageKey: 'sold',
    title: 'Esther Wambui — Vitz',
    valueKes: 1_450_000,
    assigneeEmail: 'sales@dealrstack.com',
    lastActivityAt: days(2),
    createdAt: days(16),
    inactiveDays: 2,
    conversationDemoKey: 'conv-006',
  },
  {
    demoKey: 'deal-009',
    leadDemoKey: 'lead-010',
    stageKey: 'interested',
    title: 'Charles Ndungu — LC V8 lease',
    valueKes: 18_500_000,
    assigneeEmail: 'tenant-admin@dealrstack.com',
    lastActivityAt: mins(18),
    createdAt: hours(2),
    inactiveDays: 0,
    slaDueAt: hours(2),
    conversationDemoKey: 'conv-007',
  },
] as const;

export const NAIROBI_DEMO_CONVERSATIONS = [
  {
    demoKey: 'conv-001',
    leadDemoKey: 'lead-001',
    assigneeEmail: 'sales@dealrstack.com',
    unreadCount: 2,
    lastMessagePreview: 'Can you do KES 8.2M if I pay 60% deposit?',
    lastMessageAt: mins(4),
    internalNotes: 'Trade-in: 2016 RAV4 — pending valuation.',
  },
  {
    demoKey: 'conv-002',
    leadDemoKey: 'lead-002',
    assigneeEmail: 'brian@nairobi-auto-hub.co.ke',
    unreadCount: 0,
    lastMessagePreview: 'See you Saturday 10am at Mombasa Road.',
    lastMessageAt: hours(1),
  },
  {
    demoKey: 'conv-003',
    leadDemoKey: 'lead-004',
    assigneeEmail: 'sales@dealrstack.com',
    unreadCount: 0,
    lastMessagePreview: 'Send comparison sheet for Forester vs RAV4.',
    lastMessageAt: days(1),
  },
  {
    demoKey: 'conv-004',
    leadDemoKey: 'lead-005',
    assigneeEmail: 'tenant-admin@dealrstack.com',
    unreadCount: 0,
    lastMessagePreview: 'Deposit receipt received — thanks!',
    lastMessageAt: mins(45),
  },
  {
    demoKey: 'conv-005',
    leadDemoKey: 'lead-006',
    assigneeEmail: 'sales@dealrstack.com',
    unreadCount: 3,
    lastMessagePreview: 'Is the Fit still available?',
    lastMessageAt: mins(15),
  },
  {
    demoKey: 'conv-006',
    leadDemoKey: 'lead-008',
    assigneeEmail: 'sales@dealrstack.com',
    unreadCount: 0,
    lastMessagePreview: 'Pickup scheduled Tuesday 9am.',
    lastMessageAt: days(2),
  },
  {
    demoKey: 'conv-007',
    leadDemoKey: 'lead-010',
    assigneeEmail: 'tenant-admin@dealrstack.com',
    unreadCount: 1,
    lastMessagePreview: 'Need lease terms for 36 months.',
    lastMessageAt: mins(18),
  },
] as const;

export const NAIROBI_DEMO_MESSAGES = [
  {
    demoKey: 'msg-001a',
    conversationDemoKey: 'conv-001',
    direction: MessageDirection.Inbound,
    body: 'Hi, I saw the Prado on your WhatsApp catalog.',
    sentAt: hours(3),
  },
  {
    demoKey: 'msg-001b',
    conversationDemoKey: 'conv-001',
    direction: MessageDirection.Outbound,
    body: 'Karibu Brian! The 2021 Prado is available at Westlands. Would you like financing options?',
    sentAt: hours(2),
  },
  {
    demoKey: 'msg-001c',
    conversationDemoKey: 'conv-001',
    direction: MessageDirection.Inbound,
    body: 'Can you do KES 8.2M if I pay 60% deposit?',
    sentAt: mins(4),
  },
  {
    demoKey: 'msg-005a',
    conversationDemoKey: 'conv-005',
    direction: MessageDirection.Inbound,
    body: 'Is the Fit still available?',
    sentAt: mins(15),
  },
  {
    demoKey: 'msg-007a',
    conversationDemoKey: 'conv-007',
    direction: MessageDirection.Inbound,
    body: 'Need lease terms for 36 months.',
    sentAt: mins(18),
  },
] as const;

export const NAIROBI_DEMO_ACTIVITIES = [
  {
    demoKey: 'act-001',
    leadDemoKey: 'lead-001',
    dealDemoKey: 'deal-001',
    type: SalesActivityType.FollowUp,
    summary: 'Send revised Prado quote with trade-in estimate',
    dueAt: hours(2),
    status: FollowUpStatus.Pending,
    automated: false,
    createdAt: mins(30),
  },
  {
    demoKey: 'act-002',
    leadDemoKey: 'lead-006',
    dealDemoKey: 'deal-006',
    type: SalesActivityType.FollowUp,
    summary: 'No response in 10 minutes — auto reminder to reply on WhatsApp',
    dueAt: mins(5),
    status: FollowUpStatus.Overdue,
    automated: true,
    createdAt: mins(20),
  },
  {
    demoKey: 'act-003',
    leadDemoKey: 'lead-004',
    dealDemoKey: 'deal-004',
    type: SalesActivityType.FollowUp,
    summary: 'No activity in 24 hours — manager check-in',
    dueAt: hours(1),
    status: FollowUpStatus.Pending,
    automated: true,
    createdAt: days(1),
  },
  {
    demoKey: 'act-004',
    leadDemoKey: 'lead-002',
    type: SalesActivityType.Visit,
    summary: 'Test drive — Mazda CX-5',
    dueAt: days(2),
    status: FollowUpStatus.Pending,
    automated: false,
    createdAt: hours(4),
  },
  {
    demoKey: 'act-005',
    leadDemoKey: 'lead-008',
    dealDemoKey: 'deal-008',
    type: SalesActivityType.Whatsapp,
    summary: 'Confirm vehicle pickup',
    completedAt: days(2),
    status: FollowUpStatus.Completed,
    automated: false,
    createdAt: days(3),
  },
  {
    demoKey: 'act-006',
    leadDemoKey: 'lead-003',
    dealDemoKey: 'deal-003',
    type: SalesActivityType.FollowUp,
    summary: 'Inactive 3 days — send fleet brochure',
    dueAt: days(1),
    status: FollowUpStatus.Overdue,
    automated: true,
    createdAt: days(3),
  },
] as const;

export const NAIROBI_DEMO_NOTIFICATIONS = [
  {
    demoKey: 'notif-001',
    kind: NotificationKind.NewLead,
    title: 'New WhatsApp lead',
    body: 'Brian Mwangi asked about Prado financing.',
    leadDemoKey: 'lead-001',
    read: false,
    createdAt: mins(12),
  },
  {
    demoKey: 'notif-002',
    kind: NotificationKind.CustomerReply,
    title: 'Customer replied',
    body: 'Wanjiru Maina: Is the Fit still available?',
    leadDemoKey: 'lead-006',
    read: false,
    createdAt: mins(15),
  },
  {
    demoKey: 'notif-003',
    kind: NotificationKind.MissedFollowUp,
    title: 'Follow-up overdue',
    body: 'Auto rule: no response in 10 min — lead-006',
    leadDemoKey: 'lead-006',
    read: false,
    createdAt: mins(10),
  },
  {
    demoKey: 'notif-004',
    kind: NotificationKind.Deposit,
    title: 'Deposit received',
    body: 'Samuel Ochieng paid deposit on Mercedes C200.',
    leadDemoKey: 'lead-005',
    dealDemoKey: 'deal-005',
    read: true,
    createdAt: mins(50),
  },
  {
    demoKey: 'notif-005',
    kind: NotificationKind.ReassignedLead,
    title: 'Lead reassigned',
    body: 'Unassigned Instagram lead escalated to James.',
    leadDemoKey: 'lead-006',
    read: false,
    createdAt: mins(8),
  },
  {
    demoKey: 'notif-006',
    kind: NotificationKind.Appointment,
    title: 'Test drive Saturday',
    body: 'Faith Njeri — Mazda CX-5 at Mombasa Road 10:00.',
    leadDemoKey: 'lead-002',
    read: true,
    createdAt: hours(6),
  },
] as const;

export const NAIROBI_DEMO_ASSIGNMENT_RULES = [
  {
    demoKey: 'rule-rr',
    type: AssignmentRuleType.RoundRobin,
    label: 'Round robin',
    description: 'Rotate new leads across available salespeople at the branch.',
    enabled: true,
    priority: 1,
  },
  {
    demoKey: 'rule-branch',
    type: AssignmentRuleType.Branch,
    label: 'Branch routing',
    description:
      'Assign leads to staff at Westlands or Mombasa Road based on listing location.',
    enabled: true,
    priority: 2,
  },
  {
    demoKey: 'rule-vehicle',
    type: AssignmentRuleType.VehicleType,
    label: 'Vehicle type',
    description:
      'Route SUV/truck inquiries to specialists with higher close rates.',
    enabled: true,
    priority: 3,
  },
  {
    demoKey: 'rule-geo',
    type: AssignmentRuleType.Geography,
    label: 'Geography',
    description:
      'Prefer reps covering Kiambu, Westlands, or South B based on customer area.',
    enabled: true,
    priority: 4,
  },
  {
    demoKey: 'rule-avail',
    type: AssignmentRuleType.Availability,
    label: 'Availability',
    description: 'Skip offline reps; escalate urgent leads to managers.',
    enabled: true,
    priority: 5,
  },
  {
    demoKey: 'rule-manual',
    type: AssignmentRuleType.Manual,
    label: 'Manual override',
    description:
      'Managers can reassign any lead; reason is stored on the record.',
    enabled: true,
    priority: 99,
  },
] as const;

export const NAIROBI_DEMO_FOLLOW_UP_RULES = [
  {
    demoKey: 'fup-10m',
    label: 'No response in 10 minutes',
    trigger: 'whatsapp_no_reply_10m',
    delayMinutes: 10,
    enabled: true,
  },
  {
    demoKey: 'fup-24h',
    label: 'No activity in 24 hours',
    trigger: 'lead_idle_24h',
    delayMinutes: 1440,
    enabled: true,
  },
  {
    demoKey: 'fup-3d',
    label: 'Inactive for 3 days',
    trigger: 'deal_idle_3d',
    delayMinutes: 4320,
    enabled: true,
  },
] as const;
